# Generated by Django 4.2.11 on 2024-04-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_businesshours_storetimezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='Running', max_length=20)),
                ('data', models.JSONField(null=True)),
            ],
        ),
    ]
